### ISSUE TITLE
Accessibility: Au-card-content no visual feedback on tab

### ISSUE THREAD

**Issue by aatauil** [appuniversum/ember-appuniversum#43]
au-card-content has an attribute of tabindex=1. When using using tab to navigate site an au-card-content element gets selected but gives no visual feedback. Maybe add something like
```css
 .au-card-content:focus{ 
   outline: 3px dashed yellow;
}
```
or remove tabindex=1 completely as it has no additional value when clicking on it anyway, I could be wrong on this but other then just selecting the element you can not click on it as you would on a button or link for example
